[package]
name = "bevy_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
bevy-inspector-egui = "0.28.0"
bevy_asset_loader = { version = "0.22.0", features = ["2d"] }
bevy_ecs_ldtk = "0.11.0"
bevy_rapier2d = "0.28.0"
rand = "0.8.5"
