[package]
name = "unstable_platform"
version = "0.1.0"
edition = "2021"

[dependencies]
avian2d = "0.2.0"
bevy = "0.15.0"
bevy-inspector-egui = "0.28.0"
bevy_asset_loader = { version = "0.22.0", features = ["2d"] }
bevy_rapier2d = "0.28.0"
rand = "0.8.5"
toolkit = { path = "../toolkit" }
