[package]
name = "unstable_platform"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
bevy-inspector-egui = "0.28.0"
bevy_asset_loader = "0.22.0"
bevy_rapier2d = "0.28.0"
toolkit = { path = "../toolkit" }
